name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Set up dependencies
        shell: bash
        # https://github.com/astral-sh/uv/issues/2077 https://github.com/astral-sh/uv/issues/3417
        # need to use a virtualenv here because uv doesn't yet support pip's --user flag and
        # GH actions/codespaces doesn't allow for system-level permissions
        run: |
          pip install uv==0.6.5 virtualenv==20.26.3
          uv venv
          source .venv/bin/activate
          uv sync

  bump-version:
    runs-on: ubuntu-22.04
    needs: [tests]
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Run version bump script
        run: python scripts/bump.py
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pyproject.toml src/__init__.py .bumpversion.cfg
          git commit -m "Bump version [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

  release:
    runs-on: ubuntu-22.04
    needs: [tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pull Latest Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Set up dependencies
        shell: bash
        # https://github.com/astral-sh/uv/issues/2077 https://github.com/astral-sh/uv/issues/3417
        # need to use a virtualenv here because uv doesn't yet support pip's --user flag and
        # GH actions/codespaces doesn't allow for system-level permissions
        run: |
          pip install uv==0.6.5 virtualenv==20.26.3
          uv venv
          source .venv/bin/activate
          uv sync
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        run: uv publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
      - name: Get version
        id: get_version
        run: echo "VERSION=$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.get_version.outputs.VERSION }} \
            --title "Release v${{ steps.get_version.outputs.VERSION }}" \
            --generate-notes \
            dist/*.whl dist/*.tar.gz
